{
 "title": "Galera WorkLoad Overview",
 "description": "Key metrics of galera nodes workload and performance",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,2m,5m,30m,1h,6h,1d" },
   {
    "name": "instances",
    "label": "Instance",
    "query": {
     "query": "label_values(mysql_global_status_wsrep_local_state, instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mysql_galera_variables_info{instance=~\"$instances\"}, wsrep_cluster_name)"
    }
   },
   {
    "name": "incr_interval",
    "label": "Increase Period",
    "query": "1m,10m,30m,1h,2h,3h,4h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Query Response Time Distribution",
   "type": "graph",
   "description": "Query response time counts (operations) are grouped into three buckets:\n\n* 100ms - 1s\n\n* 1s - 10s\n\n* &gt; 10s",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(\n(\n (rate(mysql_info_schema_query_response_time_seconds_bucket{le='1'}[$interval]) - on (instance) rate(mysql_info_schema_query_response_time_seconds_bucket{le='0.1'}[$interval])) or  (irate(mysql_info_schema_query_response_time_seconds_bucket{le='1'}[5m]) - on (instance) irate(mysql_info_schema_query_response_time_seconds_bucket{le='0.1'}[5m]))\n)\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "Queries 100ms - 1s - All nodes"
    },
    {
     "expr": "sum(\n(\n  (rate(mysql_info_schema_query_response_time_seconds_bucket{le='10'}[$interval])  - on (instance) rate(mysql_info_schema_query_response_time_seconds_bucket{le='1'}[$interval])) or   (irate(mysql_info_schema_query_response_time_seconds_bucket{le='10'}[5m])  - on (instance) irate(mysql_info_schema_query_response_time_seconds_bucket{le='1'}[5m]))\n  )\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "Queries 1s - 10s - All nodes"
    },
    {
     "expr": "sum(\n(\n  (rate(mysql_info_schema_query_response_time_seconds_bucket{le='100000'}[$interval])  - on (instance) rate(mysql_info_schema_query_response_time_seconds_bucket{le='10'}[$interval])) or (irate(mysql_info_schema_query_response_time_seconds_bucket{le='100000'}[5m])  - on (instance) irate(mysql_info_schema_query_response_time_seconds_bucket{le='10'}[5m]))\n)* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "Queries >10s - All nodes"
    }
   ]
  },
  {
   "title": "Average Query Response Time",
   "type": "graph",
   "description": "The Average Query Response Time graph shows information collected using the Response Time Distribution plugin sourced from [table INFORMATION_SCHEMA. QUERY_RESPONSE_TIME](https://www.percona.com/doc/percona-server/5.7/diagnostics/response_time_distribution.html#QUERY_RESPONSE_TIME). It computes this value across all queries by taking the sum of seconds divided by the count of queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(\nrate(mysql_info_schema_query_response_time_seconds_sum{}[$interval]) / rate(mysql_info_schema_query_response_time_seconds_count{}[$interval]) * 1000 or irate(mysql_info_schema_query_response_time_seconds_sum{}[5m]) / irate(mysql_info_schema_query_response_time_seconds_count{}[5m]) * 1000\n) * on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "Time - {{ instance }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg((\nrate(mysql_info_schema_query_response_time_seconds_sum{}[$interval]) / rate(mysql_info_schema_query_response_time_seconds_count{}[$interval]) * 1000 or irate(mysql_info_schema_query_response_time_seconds_sum{}[5m]) / irate(mysql_info_schema_query_response_time_seconds_count{}[5m]) * 1000\n)\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})\n",
     "legendFormat": "Avg Time"
    }
   ]
  },
  {
   "title": "Galera Questions",
   "type": "graph",
   "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "( rate(mysql_global_status_questions[$interval]) or irate(mysql_global_status_questions[5m]) ) * \non (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "Questions {{ instance }}"
    },
    {
     "expr": "sum(\n( rate(mysql_global_status_questions[$interval]) or irate(mysql_global_status_questions[5m]) ) * \non (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_slow_queries{}[$interval]) or irate(mysql_global_status_slow_queries{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "Slow Queries {{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Row Read Operations",
   "type": "graph",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(\nrate(mysql_global_status_innodb_row_ops_total{operation=~\".*read\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{operation=~\".*read\"}[5m])\n)\n\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "MySQL Rows Read/Sent",
   "type": "graph",
   "description": "**Query eff**\n",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum ((rate(mysql_global_status_rows_sent{}[$interval]) or irate(mysql_global_status_rows_sent{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
     "legendFormat": "Rows Sent {{ instance }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum ((rate(mysql_global_status_rows_read{}[$interval]) or irate(mysql_global_status_rows_read{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
     "legendFormat": "Rows Read {{ instance }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum ((rate(mysql_global_status_rows_tmp_read{}[$interval]) or irate(mysql_global_status_rows_read{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
     "legendFormat": "Rows Tmp Read {{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Row Write (Update) Operations",
   "type": "graph",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(\nrate(mysql_global_status_innodb_row_ops_total{operation=~\"updated\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{operation=~\"updated\"}[5m])\n)\n\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "MySQL Query Efficiency",
   "type": "graph",
   "description": "**Query eff**\nRows sent / Rows read",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum ((rate(mysql_global_status_rows_sent{}[$interval]) or irate(mysql_global_status_rows_sent{}[5m])) * on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}) / \nsum ((rate(mysql_global_status_rows_read{}[$interval]) or irate(mysql_global_status_rows_read{}[5m]))* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})\n\n",
     "legendFormat": "Querry eff {{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Select Scan",
   "type": "graph",
   "description": "Description: Number of joins which used a full scan of the first table. \n    Select Scan is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(\nrate(mysql_global_status_select_scan{}[$interval]) or\nirate(mysql_global_status_select_scan{}[5m])\n)\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "Select Scan {{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Row Write (Insert/Delete) Operations",
   "type": "graph",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(\nrate(mysql_global_status_innodb_row_ops_total{operation!~\".*read|updated\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{operation!~\".*read|updated\"}[5m])\n)\n\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "MySQL Select Full Join",
   "type": "graph",
   "description": "Description: Number of joins which did not use an index. If not zero, you may need to check table indexes. \n    Select Full Join is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(\nrate(mysql_global_status_select_full_join{}[$interval]) + rate(mysql_global_status_select_full_range_join{}[$interval]) \n or irate(mysql_global_status_select_full_join{}[5m]) + irate(mysql_global_status_select_full_range_join{}[5m])\n)\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "Full Join (+Range J)  {{ instance}}"
    }
   ]
  },
  {
   "title": "Galera InnoDB I/O - Reads",
   "type": "graph",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_data_reads{}[$interval]) or irate(mysql_global_status_innodb_data_reads{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} - Data Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[5m])",
     "legendFormat": "Log Fsyncs"
    }
   ]
  },
  {
   "title": "InnoDB Waits",
   "type": "graph",
   "description": " Total time in milliseconds spent getting InnoDB row locks. / Number of times InnoDB had to wait before getting a row lock.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(rate(mysql_global_status_innodb_row_lock_time{}[$interval])/rate(mysql_global_status_innodb_row_lock_waits{}[$interval]) * on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}) or (rate(mysql_global_status_innodb_row_lock_time{}[5m])/rate(mysql_global_status_innodb_row_lock_waits{}[5m]))* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n",
     "legendFormat": "Avg Row Lock Time - {{ instance }}"
    }
   ]
  },
  {
   "title": "Galera InnoDB I/O - Writes",
   "type": "graph",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(\n(rate(mysql_global_status_innodb_data_writes{}[$interval]) or irate(mysql_global_status_innodb_data_writes{}[5m])  ) \n)\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} - Data Writes"
    },
    {
     "expr": "max(mysql_global_variables_innodb_io_capacity\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "io_capacity (largest of nodes)"
    }
   ]
  },
  {
   "title": "Galera InnoDB Page I/O",
   "type": "graph",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_pages_read{}[$interval]) or irate(mysql_global_status_innodb_pages_read{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} - Pages Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_pages_written{}[$interval]) or irate(mysql_global_status_innodb_pages_written{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} - Pages Written"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum ( (rate(mysql_global_status_innodb_pages_created{}[$interval]) or irate(mysql_global_status_innodb_pages_created{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
     "legendFormat": "All - Pages Created"
    }
   ]
  },
  {
   "title": "Galera InnoDB I/O",
   "type": "graph",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_data_reads{}[$interval]) or irate(mysql_global_status_innodb_data_reads{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} - Data Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(\n(rate(mysql_global_status_innodb_data_writes{}[$interval]) or irate(mysql_global_status_innodb_data_writes{}[5m])  ) + \n(rate(mysql_global_status_innodb_log_writes{}[$interval]) or irate(mysql_global_status_innodb_log_writes{}[5m]))\n)\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} - Data+Log Writes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$host\"}[5m])",
     "legendFormat": "Log Fsyncs"
    }
   ]
  },
  {
   "title": "InnoDB Checkpoint Age (LSN diff) (innodb metrics)",
   "type": "graph",
   "description": "**InnoDB Checkpoint Age**\n\nThe maximum checkpoint age is determined by the total length of all transaction log files (`innodb_log_file_size`).\n\nWhen the checkpoint age reaches the maximum checkpoint age, blocks are flushed syncronously. The rules of the thumb is to keep one hour of traffic in those logs and let the checkpointing perform its work as smooth as possible. If you don't do this, InnoDB will do synchronous flushing at the worst possible time, ie when you are busiest.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(max_over_time(mysql_info_schema_innodb_metrics_recovery_log_lsn_checkpoint_age_total[$interval]) or\nmax_over_time(mysql_info_schema_innodb_metrics_recovery_log_lsn_checkpoint_age_total[5m])) \n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "Uncheckpointed {{ instance }}"
    },
    {
     "expr": "max(mysql_global_variables_innodb_log_files_in_group{} * mysql_global_variables_innodb_log_file_size{} * on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
     "legendFormat": "Log size (max)"
    },
    {
     "expr": "min(mysql_global_variables_innodb_adaptive_flushing_lwm/100 * mysql_global_variables_innodb_adaptive_flushing * mysql_global_variables_innodb_log_files_in_group * mysql_global_variables_innodb_log_file_size\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
     "legendFormat": "Adaptive flushing LWM min"
    },
    {
     "expr": "max(mysql_global_variables_innodb_adaptive_flushing_lwm/100 * mysql_global_variables_innodb_adaptive_flushing * mysql_global_variables_innodb_log_files_in_group * mysql_global_variables_innodb_log_file_size\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
     "legendFormat": "Adaptive flushing LWM max"
    }
   ]
  },
  {
   "title": "InnoDB Throughput - Read Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_data_read[$interval]) or irate(mysql_global_status_innodb_data_read[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} - Data Read Bytes "
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Dirty",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{instance }} Dirty"
    }
   ]
  },
  {
   "title": "InnoDB Throughput - Written Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "min(\n(rate(mysql_global_status_innodb_os_log_written[$interval]) or irate(mysql_global_status_innodb_os_log_written[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "min of nodes - Log Writen Bytes "
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_data_written[$interval]) or irate(mysql_global_status_innodb_data_written[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} - Data Writen Bytes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max(\n(rate(mysql_global_status_innodb_os_log_written[$interval]) or irate(mysql_global_status_innodb_os_log_written[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "max of nodes - Log Writen Bytes "
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Pages (free)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_buffer_pool_pages{state=~\"free\"} \n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ state }} {{instance }}"
    }
   ]
  },
  {
   "title": "Galera InnoDB Fsyncs Data/Log (+/-)",
   "type": "graph",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_data_fsyncs{}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{}[5m]))\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "Data Fsyncs - {{instance }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_innodb_os_log_fsyncs{}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{}[5m])) \n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "Log Fsyncs {{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_data\n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{instance }} Data"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk (5,\nsum by (command) (\n(\nrate(mysql_global_status_commands_total{}[$interval])>0 or irate(mysql_global_status_commands_total{}[5m])>0\n)* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)\n)\n",
     "legendFormat": "Com_{{ command }} {{ instance}}"
    }
   ]
  },
  {
   "title": "Top Command Counters (increase per $incr_interval)",
   "type": "graph",
   "description": "**Top Command Counters Hourly**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5,\n  sum by (command) (\n    increase (mysql_global_status_commands_total{}[$incr_interval])\n    * on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n  )>0\n  )\n\n",
     "legendFormat": "Com_{{ command }} {{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers (commit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{handler=~\"commit\"}[$interval]) \n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ handler }} {{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers (commit) (incr $incr_interval)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_handlers_total{handler=~\"commit\"}[$incr_interval]) \n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ handler }} {{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers (rollback)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{handler=~\"rollback\"}[$interval]) \n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ handler }} {{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers (rollback) (incr $incr_interval)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_handlers_total{handler=~\"rollback\"}[$incr_interval]) \n* on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ handler }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Flow Control Paused Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp_max((rate(mysql_global_status_wsrep_flow_control_paused_ns[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns[5m]))/1000000000 * on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"},1)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Galera Sql Network Traffic",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n( rate(mysql_global_status_bytes_received{}[$interval]) or irate(mysql_global_status_bytes_received{}[5m]) )\n * \non (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n( rate(mysql_global_status_bytes_sent{}[$interval]) or irate(mysql_global_status_bytes_sent{}[5m]) )\n * \non (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}\n)",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Average Galera Replication Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(mysql_galera_evs_repl_latency_avg_seconds[$interval]) * on (instance) group_left mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"}",
     "legendFormat": "{{instance}} - Latency Average"
    }
   ]
  }
 ]
}